/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.HiloJuego;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.net.URL;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author Estudiante
 */
public class FRM_AreaJuego extends javax.swing.JFrame {

    String estadoPersonaje = "suelo";
    HiloJuego hilo;
    private Clip sonidoFondo;

    /**
     * Creates new form FRM_AreaJuego
     */
    public FRM_AreaJuego() {
        initComponents();
        setLocation(100, 100);
        jlPersonaje.setLocation(200, 400);
        hilo = new HiloJuego(this);
        hilo.start();
        try {
            sonidoFondo = AudioSystem.getClip();
            sonidoFondo.open(AudioSystem.getAudioInputStream(getClass().getResource("/musica/main.wav")));
            sonidoFondo.loop(1);
        } catch (Exception e) {
            e.getMessage();
        }
    }// Fin del constructor

    public void moverFondo() {
        if (jlFondo.getX() > -170) {
            //Esto es para correr el fondo a la izquierda siempre y cuando sea su margen mayor a -170
            jlFondo.setLocation(jlFondo.getX() - 1, jlFondo.getY());
        } else {
            //Esta linea devuelve el fondo a la posicion original
            jlFondo.setLocation(0, jlFondo.getY());
        }

    }//fin del metodo

    public void moverPersonaje() {
        if (estadoPersonaje.equals("subiendo")) {
            jlPersonaje.setLocation(jlPersonaje.getX() + 1, jlPersonaje.getY() - 5);
        }
        if (jlPersonaje.getY() < 20) {
            estadoPersonaje = "bajando";
        }
        if (estadoPersonaje.equals("bajando")) {
            jlPersonaje.setLocation(jlPersonaje.getX(), jlPersonaje.getY() + 5);
        }

        if (jlPersonaje.getY() >= 342) {
            estadoPersonaje = "suelo";
        }

    }

    public void moverMalo() {
        jlMalo.setLocation(jlMalo.getX() - 2, jlMalo.getY());
        if (jlMalo.getX() < -50) { 
            reproducirSonido(getClass().getResource("/musica/grito.wav"));
            jlMalo.setLocation(1300, jlMalo.getY());
            
        }

    }

    public void moverDisparo() {
        jlDisparo.setLocation(jlDisparo.getX() - 6, jlDisparo.getY());
        if (jlDisparo.getX() < -50) {
            jlDisparo.setLocation(jlMalo.getX() - 5, jlDisparo.getY());
            reproducirSonido(getClass().getResource("/musica/disparo.wav"));
        }
    }//Fin de moverDisparo

    
    public void detectarColision() {
        if (jlMalo.getX() < (jlPersonaje.getX() + 115)
                && (jlPersonaje.getY() + 35) < jlMalo.getY()
                && (jlMalo.getX() + 110) > jlPersonaje.getX()) {
            System.out.print("Yogurt");
            hilo.gameOver = true;
            reproducirSonido(getClass().getResource("/musica/muerte.wav"));
        }  
    }
    
    public void detectarDisparo() {
        if (jlDisparo.getX() < (jlPersonaje.getX() + 145)
                && (jlDisparo.getX() + 145) > jlPersonaje.getX()
                && (jlPersonaje.getY() + 75) > jlDisparo.getY()) {
            System.out.print("Yogurt");
            reproducirSonido(getClass().getResource("/musica/muerte.wav"));
            hilo.gameOver = true;
        }

    }

    public void mensaje(String mensaje) {
        Icon icono = new ImageIcon(getClass().getResource("/img/icon.gif"));
        JOptionPane.showMessageDialog(null, mensaje, "Perdiste!!", JOptionPane.ERROR_MESSAGE, icono);

    }

    public static void reproducirSonido(URL ruta) {
        try {
            Clip sonido = AudioSystem.getClip();
            sonido.open(AudioSystem.getAudioInputStream(ruta));
            if (!sonido.isRunning()) {
                sonido.start();
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlPersonaje = new javax.swing.JLabel();
        jlMalo = new javax.swing.JLabel();
        jlDisparo = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/h2.gif"))); // NOI18N
        getContentPane().add(jlPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 350, 242, -1));

        jlMalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.gif"))); // NOI18N
        getContentPane().add(jlMalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 340, 272, 208));

        jlDisparo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/f.gif"))); // NOI18N
        getContentPane().add(jlDisparo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 410, -1, 30));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pantano.jpg"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 10, 1680, 553));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == 32) {
            estadoPersonaje = "subiendo";
            try {
                reproducirSonido(getClass().getResource("/musica/Salto.wav"));
            } catch (Exception e) {
                e.getMessage();
            }

        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_AreaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_AreaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_AreaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_AreaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_AreaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlDisparo;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlMalo;
    private javax.swing.JLabel jlPersonaje;
    // End of variables declaration//GEN-END:variables

   
}
