/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Usuario
 */
public class Panel_Laberinto extends javax.swing.JPanel {
  private int fila=0;
    private int columna=0;
    private final int numeroFilas=13;
    private final int numerodeColumnas=23;
    public final int anchoBloque=60;
    public final int altoBloque=60;
    /**
     * Creates new form Panel_Laberinto
     */
    public Panel_Laberinto() {
        initComponents();
        
    
    }
    @Override
protected void paintComponent(Graphics grafico) {
    super.paintComponent(grafico);

    int[][] laberinto = obtnerlaberinto();
    for (int fila = 0; fila < laberinto.length; fila++) {
        for (int columna = 0; columna < laberinto[fila].length; columna++) {
            if (laberinto[fila][columna] == 1) {
                grafico.setColor(Color.pink);
                grafico.fill3DRect(columna * anchoBloque, fila * altoBloque, anchoBloque, altoBloque, true);
                grafico.setColor(Color.pink);
                grafico.draw3DRect(columna * anchoBloque, fila * altoBloque, anchoBloque, altoBloque, true);
                
            }
            
        }
    }
}

    public int[][] obtnerlaberinto() {
    int[][] laberinto = {
        {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,1},
        {1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,1},
        {1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,1},
        {1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,1},
        {1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,1},
        {1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,1},
        {1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,1},
        {1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,0, 0,1},
        {1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,1},
        {1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,1},
        {1, 1, 0, 1, 1, 0, 1, 1, 1 ,0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,1},
        {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,1},
        {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,1}
       
    };

    return laberinto;
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
